### ISSUE TITLE
TvShowTreeView.cpp compile problem on Fedora 37

### ISSUE THREAD

**Issue by stevefalco** [Komet/MediaElch#1525]
**Describe the bug**
I'm trying to compile on Fedora 37 x86_64, and I get an error from g++:

```
../src/ui/small_widgets/TvShowTreeView.cpp: In member function ‘void TvShowTreeView::drawTvShowRow(QPainter*, const QStyleOptionViewItem&, const QModelIndex&) const’:
../src/ui/small_widgets/TvShowTreeView.cpp:140:5: error: invalid use of member function ‘const QFont& QWidget::font() const’ (did you forget the ‘()’ ?)
  140 |     font.setPointSize(font.pointSize() - 1);
      |     ^~~~
      |         ()
make: *** [Makefile:22022: TvShowTreeView.o] Error 1

```

I've been able to work around it by changing `font.setPointSize(font.pointSize() - 1);` to `textFont.setPointSize(textFont.pointSize() - 2);` as is done for Macintosh builds.

**To Reproduce**
1. Compile on Fedora 37.

**Expected behavior**
No compiler error

**Screenshots**

**MediaElch Version:**
 - [X] 2.8.19-dev (nightly)
 - [ ] 2.8.18 stable

**Operating System:**
 - [ ] Windows
 - [ ] macOS
 - [X] Linux (distribution: Fedora 37)

**Additional context**

**Comment by bugwelle** [comment]
Thanks for reporting it! Indeed, the our Jenkins builds are failing for non-macOS... 

Was broken after https://github.com/Komet/MediaElch/commit/429185d8d60ef5d88bbeaa113530ad57b3205cf6 . 
I need to integrate the Jenkins pipeline into our PR system again (it currently only runs on my fork...).
